### PR TITLE
Osx build fix (check for safe str functions presence)

### PR DESCRIPTION
**Pull request by dimxy**
fixed check for strlcpy/cat safe funcs
fixed call param to Pair

### CODE REVIEW

**Review by DeckerSU — CHANGES_REQUESTED** [review]
Plz, add the following changes:
```
---
 src/cryptoconditions/src/strl.c | 4 ++--
 src/cryptoconditions/src/strl.h | 4 ++--
 2 files changed, 4 insertions(+), 4 deletions(-)

diff --git a/src/cryptoconditions/src/strl.c b/src/cryptoconditions/src/strl.c
index e326aae..79a2e55 100644
--- a/src/cryptoconditions/src/strl.c
+++ b/src/cryptoconditions/src/strl.c
@@ -21,7 +21,7 @@
  * chars will be copied.  Always NUL terminates (unless dsize == 0).
  * Returns strlen(src); if retval >= dsize, truncation occurred.
  */
-#ifndef HAVE_DECL_STRLCPY
+#if HAVE_DECL_STRLCPY == 0
 size_t
 strlcpy(char *dst, const char *src, size_t dsize)
 {
@@ -55,7 +55,7 @@ strlcpy(char *dst, const char *src, size_t dsize)
  * Returns strlen(src) + MIN(dsize, strlen(initial dst)).
  * If retval >= dsize, truncation occurred.
  */
-#ifndef HAVE_DECL_STRLCAT
+#if HAVE_DECL_STRLCAT == 0
 size_t
 strlcat(char *dst, const char *src, size_t dsize)
 {
diff --git a/src/cryptoconditions/src/strl.h b/src/cryptoconditions/src/strl.h
index 04a235b..80b680a 100644
--- a/src/cryptoconditions/src/strl.h
+++ b/src/cryptoconditions/src/strl.h
@@ -13,12 +13,12 @@
 extern "C" {
 #endif
 
-#ifndef HAVE_DECL_STRLCPY
+#if HAVE_DECL_STRLCPY == 0
 size_t
 strlcpy(char *dst, const char *src, size_t dsize);
 #endif
 
-#ifndef HAVE_DECL_STRLCAT
+#if HAVE_DECL_STRLCAT == 0
 size_t
 strlcat(char *dst, const char *src, size_t dsize);
 #endif
-- 
```
Otherwise other OS builds will fail.

In other words, we need to change all occurrences of:
```
#ifndef HAVE_DECL_STRLSOMETHING
```
on
```
#if HAVE_DECL_STRLSOMETHING == 0
```
inside `src/cryptoconditions/src/strl.c` and `src/cryptoconditions/src/strl.h`.

**Comment by dimxy** [comment]
ah sorry my bad (seems I forgot to run autogen when tested on linux)
then I suggest change these macros a bit like that:
```
#if !defined(HAVE_DECL_STRLCPY) || HAVE_DECL_STRLCPY == 0
```

**Comment by dimxy** [comment]
I'd suggest adding build-xxx.sh scripts for mac/lin/mingw it seems they are pretty handy

**Review by DeckerSU — APPROVED** [review]
LGTM now. Linux and Windows (MinGW) builds now are fine.

**p.s.** About adding build scripts for various platfroms, why not? But i prefer to do that in other PR.

**Pull request merged**
